name: react-native-template
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Run tests
        run: |
          npm test
      - name: Build android
        run: npm run build-android
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/